#!/usr/bin/env bash
# Placeholder generated by converter.
# This file was generated automatically because `/home/toor/code/agents/plugins/security-scanning/skills/sast-configuration/SKILL.md` references `scripts/run-sast.sh`, but the source repository did not provide that file.
exit 0
